version: "3.9"

name: inception

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  credentials:
    file: ../secrets/credentials.txt

networks:
  inception-net:

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOST_DATA}/db
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOST_DATA}/wp


services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    image: mariadb:${MARIADB_VERSION}-local
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    secrets:
      - db_password
      - db_root_password
    volumes:
      - "${USERPROFILE}/data/db:/var/lib/mysql"
    networks:
      - inception-net
    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -h 127.0.0.1 -uroot -p$$(cat /run/secrets/db_root_password) || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  wp-php:
    container_name: wp-php
    build:
      context: ./requirements/wordpress
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
        PHP_VERSION: ${PHP_VERSION}
    image: wordpress-php:${PHP_VERSION}-local
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_URL: ${WP_URL}
    depends_on:
      mariadb:
        condition: service_healthy
    secrets:
      - db_password
      - credentials
    volumes:
      - "${USERPROFILE}/data/wp:/var/www/html"
    networks:
      - inception-net

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    image: nginx:${NGINX_VERSION}-local
    restart: always
    depends_on:
      - wp-php
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "443:443"
    volumes:
      - "${USERPROFILE}/data/wp:/var/www/html:ro"
    networks:
      - inception-net
