# version: "3.5"

volumes:
  dbdata:
  wpdata:

services:
  mariadb:
    build: ./requirements/mariadb
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: change_me
      MARIADB_DATABASE: wp_db
      MARIADB_USER: wp_user
      MARIADB_PASSWORD: wp_pass
      MARIADB_AUTO_UPGRADE: "1"
    restart: always
    ports:
      - "127.0.0.1:3306:3306"

  wordpress:
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wpdata:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
    restart: always

  nginx:
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"
    volumes:
      - wpdata:/var/www/html:ro 
      - ./requirements/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./requirements/nginx/certs:/etc/nginx/certs:ro
    restart: always
